import "./App.css";
import LottieBackground from "./Components/LottieBackground";
import GithubCalendar from "./GithubCalendar";
import Navbar from "./Navbar";

function App() {
  return (
    <>
      <LottieBackground />
      <main className="relative z-10">
        <Navbar></Navbar>
        <GithubCalendar></GithubCalendar>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Omnis, minus quaerat libero veniam expedita officiis optio commodi, labore magni quia facilis! Deserunt neque minima iusto ullam? Dolore tempora vitae facilis quos in sapiente deserunt similique, quasi esse, sed ducimus quas vero illo impedit sit suscipit molestiae obcaecati quia eum facere corporis! Harum saepe aliquam, aperiam error magni laboriosam quae perspiciatis. Deleniti consectetur minima voluptates numquam illo saepe provident, distinctio assumenda laborum magnam dolore optio ipsum! Voluptatem deleniti magni natus maiores quo reiciendis neque rerum optio nemo blanditiis quidem sunt laboriosam, dicta asperiores commodi pariatur doloremque quaerat soluta ducimus fuga. Soluta.</p>
      </main>
    </>
  );
}

export default App;
